BBBBBBB BBBBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXX
	XXXX XXXXXXXXX XXXXXXXXXXX
		XXXX XXXXXXXXX XXXXXX
			BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
			XXXX XXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXX
				BBBBBBB BBBBBBBBBBBBBBBBBBBB
				XXX XXXXXXXXX XXX XXXXXXXX XXXXXXXX
					XXXXXXXXXXXXXXXXXXXXXXX
				XXXXX
				XXXX XXXXXXXXX XXXXXXXX XXXXXXXXX
					XXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXX XXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXBBBBBBBBBB
						XXXX XXXXXXXXXXXXXXX XXXXXXX
							XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
							XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXX
							XX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXX
						XXXX XXXXXXXXXXXXXX
							XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
							XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX
						XXXXXX
						XXXX XXXXXXXXXXXXXXX XXXXXXX
							XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
							XXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXX
						XXXXXX
						XXXX XXXXXXXXXXXXXX
							XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
							XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX
						XXXXXX
						XXXX XXXXXXXXXXXXXX
							XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
							XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX  XXXXXXXXX
						XXXXXX

						XXXX XXXXXXXXXXXXXX
							XXXXXXX XXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXX
					XXXXXXX
				XXXXXX
			XXXXXX
		XXXXXX
	XXXXXX
XXXXXX
BBBBBBB BBBBBBBBBBBBBBBBBBBBB
