XXXXXXXXX XXXXX

XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXX XXXXXX XXXXXXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXX
XXXX XXXXXXX
  XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX
  XXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXX
XXXXXX

XXXXXXXXX
XXXXXXXX XXXXXXXXX
XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX
BBBBBBB BBBBBBBBBBBBB
BBBBB BBBBBXXXXXXXXXXX XXXX XXXXBBBBBBBB

BBBBB BBBBBBB
  BBB BBB BB BBB BB BBBBBBB BB BBBBBBBBB BBBBB
    XXXXX 
  BBBB
    BBB BBB B BBBBBBB BBB BBBBBB
    BBBBBBB BBBBBBBBBBBB BBBB B BBBBBBBB BBB B
  BBBBBB
BBBBBBBB
XXXXXXXXXXXXXXXXXX
    XXXXXXXX
      XXX XXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXX XXXXXXX XXXXXXXXX XXXXXXXX
    XXXXXXXXX
  XXXXXXXXXX
