BBBBBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBB

XXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXX XX X XXXX XXX XXXXXXXXX XXX XXXXXXXX XXXXX XXX XXXXX XXX XXX XXXXXXXXXXXX XXXXX XXXXX XXX XXX XXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
XXXXXX

XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXX XXXXXXXXXXXX
        XXX
            XXXXXX XXXXX XXX X XXXXXXXXX XXXXXXXXXXXXXX XXX XX XXXXX XXXXXXX XXXXXXXX XXXX
            XXXXXXX X XXXXX XXXXXXXXXX XX XXXXXXXX XXX XXXXX XXX XXXX XXXXXXX XXXX XXXXXX
            XXX XXXXXXXXXX XXXXX XXXXXXXXXXXX
        XXXX
        XXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXXXXX XXXX XXXXXXXXXXXXXX
        XXXXXX XXXXXX XXXXXXX XXXXX XX X XXXXXXXXXX XX XXXXXXXX XXX XXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
        XXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX XXXXXXXXXX
        XXXXXX XXX XXXXXX XXXXXXX XX XXXXXXXXX XXXXX XXXXX XXXXXX XXXXX XXX XXXXXX XXXXXXX XXXX XXX XXX XXX XXX XXXX XXXX XXXXXXXXXXX XXXXX X XXXX XXXXX XXXXXXXXXX
        XXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
    XXXXXX
XXXXXX

BBBBBBBB
