BB BBBBBBBBBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    BBBBBBBBBB
    XXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXX

XXXXXXX

BBBB

XXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXX XXXXXXBBB BBBBBBBXXXXX XXXXXXXXXXX
XXXXX

BBBBB
