BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX
	XXXX XXXXXXXXX XXXXXXXXXXX
		XXXX XXXXXXXXX XXXXXX
			BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
			XXXX XXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXX
				BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
				XXX XXXXXXXXX XXX XXXXXXXX XXXXXXXX
					XXXXXXXXXXXXXXXXXXXXXXXX
				XXXXX
				XXXX XXXXXXXXX XXXXXXXX XXXXXXXXX
					XXXXX XXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXBBBBBBBBBB
						XXXX XXXXXXXXXXXXXXX XXXXXXX
							XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
							XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
						XXXXXX
						XXXX XXXXXXXXXXXXXXX XXXXXXX
							XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
							XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
						XXXXXX
						XXXX XXXXXXXXXXXXXXX XXXXXXX
							XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
							XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
						XXXXXX

						XXXX XXXXXXXXXXXXXX
							XXXXXXX XXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXX
					XXXXXXX
					XXXX XXXXXXXXX XXXX XXXXXXXXX
						XX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXX
				XXXXXX
			XXXXXX
		XXXXXX
	XXXXXX
XXXXXX
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
